### ISSUE TITLE
Improved Logging for Worker Threads

### ISSUE THREAD

**Issue by definitelysean** [compbiomed/celda#109]
celda currently always uses doParallel in order to run models, including if you just ask for 1 core. 
This yields several problems: it makes debugging complex model code really hard (because debugging messages are lost en route to the master process), and R CMD check with --as-cran gets _really mad_ when you try to use parallel code to run tests.

One way to improve the debugging angle would be to _improve logging._ If we could use sink() to change the stderr/stdout for each celda worker thread to a file unique to that thread, hopefully we would get full stack traces that will be more informative than the messages fed to the parent process through forEach/doParallel.

**Comment by definitelysean** [comment]
@joshua-d-campbell @87875172  You guys can look at the commit in this issue to see how I implemented the logging. You basically need to open a file object (with file()) and then pass that as the first argument to sink(). Also, it's recommended that when you're done using that log file, you call sink() again with no parameters.

**Comment by joshua-d-campbell** [comment]
Thanks for trying this out @definitelysean. After test running it, there was an issue that If the user interrupts with control-c or if there is an error, the file connection will remain open and any additional output will be redirected with sink until the file connection is manually closed. Also, the logging when using the celda wrapper doesn't record other parameters that may be tested like alpha, beta, etc. 

I refactored it by writing an additional "log_messages" function that will print a message as normal if no filename is given or will use 'cat' to write the message out to a file if a filename is given. By using cat, the file handle is opened and closed right away. Messages that come after the first will be appended to the existing file.

For the celda wrapper, I generate a file name within the wrapper that is passed to the celda_* functions. The file name contains all of the parameters. This also alleviates the need to pass a "Thread" parameter for logging as the chain will be present in the file name.
