### ISSUE TITLE
could not find function "cCG.calcLL" on scc

### ISSUE THREAD

**Issue by 87875172** [compbiomed/celda#118]
Running celda() on scc throws the error "could not find function c*.calcLL" depending on the celda model being run.

**Comment by definitelysean** [comment]
I think this might be an environment issue since @ykoga07 and I can't reproduce it.
Can you try putting the following in your ~/.bashrc and then reinstalling celda via install_github(), without setting the library path?

`export R_LIBS_USER='~/Rlib:/restricted/projectnb/cbmhive/R_packages/R-%V'`
