### ISSUE TITLE
render_celda_heatmap heatmap default normalized minimum expression value in legend is not -2

### ISSUE THREAD

**Issue by 87875172** [compbiomed/celda#121]
The default output heatmap by render_celda_heatmap generates legend with value range between [-1, 2]. It should be between [-2, 2]. Probably some scaling issue.

**Comment by 87875172** [comment]
This has something to do with the data where most of the genes for a cell have counts zero and is not a problem of the function.

**Comment by definitelysean** [comment]
Hey @Irisapo , any input on this issue?

**Comment by Irisapo** [comment]
Will have a look at this !!

**Comment by Irisapo** [comment]
Does this mean that the legend should be symmetric to 0 when 0 is covered within the values range ? @87875172

**Comment by Irisapo** [comment]
Or is it because of the z_trim that the minimum should be -2  ?

**Comment by 87875172** [comment]
Yes, the legend should be symmetric with respect to 0. When the minimum value in the count matrix is larger than -2, the lower bound in the legend should be -2 instead of the minimum value in the count matrix. Same with upper bound. I sent you two heatmaps illustrating the one with lower bound issue and the correct one. Let me know if you have more questions. @Irisapo
