### ISSUE TITLE
Profile Cluster Assignment Evaluation Frequency

### ISSUE THREAD

**Issue by definitelysean** [compbiomed/celda#123]
We should evaluate whether it'd be useful to cache the log likelihood of a given cluster assignment for future lookup. To do so, we can run some celda model simulations, emitting every cluster assignment from every thread into a common place, and looking at how many times the same assignment was calculated (as well as the time-to-calculate for each).

It's probably not the biggest timesink in the code right now, but worth looking at in some spare time.

**Comment by joshua-d-campbell** [comment]
I think this will be difficult to implement and probably not worth it and doesn't really jive with how the Gibbs sampling works. I'm going to close for now.
