### ISSUE TITLE
Typo in previous semi_pheatmap.R commit

### ISSUE THREAD

**Issue by 87875172** [compbiomed/celda#141]
https://github.com/compbiomed/celda/blob/9968b75bf28d1ec1232068250a03f3923fb027a5/R/semi_pheatmap.R#L586

return(stats::hclust(stats::dist(mat =  mat[class.pos,], distance = distance ),method = method ))
should be 
return(stats::hclust(dis(mat =  mat[class.pos,], distance = distance ),method = method ))

**Comment by definitelysean** [comment]
@87875172 Looks like you added some commits to this; can you close the issue if you're done?

**Comment by 87875172** [comment]
@definitelysean I think the issue will be closed automatically once the pull request is approved, is that right? Can you approve my pull request and I'll close the issue afterwards.
