### ISSUE TITLE
plot_dr functions

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#150]
1) plot_dr_cluster => use distinct_clusters() to color points rather than ggplot2 default color scheme
2) plot_dr_states => rescale set to True in default, legend label = "Scaled Probability" if scaled, "Probability" if not
3) all dr plots => add a parameter for "color_mid" set to NULL by default. If NULL then plot as normal, If not NULL, the plot divergent color scheme using scale_colour_gradient2
4) Add ggplot:: to aes_string

**Comment by definitelysean** [comment]
Another good thing to do would be to change the function names to use camelCase, per #137 (so, potentially change occurances of plot_dr_cluster to plotDrCluster)
