### ISSUE TITLE
modelBest vs. modelSubset function

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#153]
For a res list from celda wrapper. It would be nice to have two separate functions, one for subsetting a list based on matching rows in the run.params object, and another one for choosing the best model in a list based on loglik or perplexity.

**Comment by definitelysean** [comment]
For your second use case, is `getModel()` suitable?
The first case should be straightforward, as some of the internals `getModel()` relies on do exactly what you described, just for a single row.

**Comment by definitelysean** [comment]
Hey @joshua-d-campbell , can you check out `selectModel()` on the master branch and let me know if that covers your desired functionality?

**Comment by joshua-d-campbell** [comment]
Originally I was thinking that "selectModel" would be the current "getModel" but without the "best" option. I.e. that it would return all models that meet a certain criteria such as K=10, chain = 1:5, or index = 300. Then a second function "bestModel" would return the model with the best likelihood from the list of models. So the user would have to call two functions to get down to a single model, but it would be clearer what each function is doing.

However, now I'm just wondering if we should only return the celda list where only the best models are already selected for each combination of K, L, etc. I don't see a case where returning chains that weren't the best would be desirable.

**Comment by definitelysean** [comment]
I think the potential pitfall would be that "best" might have different definitions depending on the use case. 
Should we add additional parameters to the `celda()` wrapper to pre-define the criteria for which model should be returned?

I'll try to wrap all of the functionality you described into getModel() anyways, as we'll need it internally if we take the approach above. Just for propriety's sake, does the below list include all parameters the user might want to select a model by?

- Row index in run params
- K/L 
- chain number

**Comment by definitelysean** [comment]
@joshua-d-campbell I can tackle this one, but do you want to include a switch in the celda wrapper that only returns the best chain for each K/L combination?

**Comment by joshua-d-campbell** [comment]
Yes that's fine to include a switch with default equal to TRUE. That will make the output simpler but leave some flexibility.

**Comment by definitelysean** [comment]
Implemented all of the above in https://github.com/compbiomed/celda/commit/694bc2baa43335609dc9a259c957bfcf4f4eb5bb
