### ISSUE TITLE
plotDrCluster errors

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#163]
1) When running without first loading ggplot2, I get the following error:

> plotDrCluster(tsne$Y[,1], tsne$Y[,2], model$z)
Error in mget(args, envir = env) : could not find function "element_line"

2) When the cluster variable is not entered as a factor, I get the following error:
> plotDrCluster(tsne$Y[,1], tsne$Y[,2], model$z)
Error: Continuous value supplied to discrete scale

If cluster label is supplied as a numeric (e.g. model$z from celda result), it should be internally converted to a factor without throwing an error

**Comment by definitelysean** [comment]
@Jiangyuan-Liu @ykoga07 Was this addressed in the most recent commit? Can we close this one?

**Comment by Jiangyuan-Liu** [comment]
Yes. It was fixed.

**Comment by definitelysean** [comment]
@Jiangyuan-Liu thanks, I'll close this issue.
