### ISSUE TITLE
vignette function name obsolete

### ISSUE THREAD

**Issue by chlee-tabin** [compbiomed/celda#169]
When running ver0.3, render_celda_heatmap (as described in the vignette) is not found. renderCeldaHeatmap could be found and reproduces the plot.

factorizeMatrix.celda_CG also is not found.

**Comment by definitelysean** [comment]
Thanks for reporting this, @chlee-tabin. The wrong commit was tagged for v0.3; if you reinstall at that tag, you should see the most up-to-date vignette.

**Comment by chlee-tabin** [comment]
Sorry I may be not doing it right: I removed the package, then did library(devtools), install_github("compbiomed/celda@v0.3"), and ran vignette("celda-analysis"). Still showing up the 2017-09-19 vignette with the wrong function names.

**Comment by definitelysean** [comment]
@chlee-tabin Sorry! I realized the problem. The updated vignette was under vignettes/ , but wasn't moved to inst/doc, so wasn't discoverable by the vignette() function. I'll make sure to rebuild the vignette and make it accessible this way. Thank you for pointing that out!

In the meantime, you can reference the .html file in the vignettes/ directory if you need help using this package.

**Comment by chlee-tabin** [comment]
Thank you! I wanted to try out celda, and the outdated vignette was making me hesitate whether I installed the overall code correctly. Hope it gets fixed soon!

**Comment by definitelysean** [comment]
Hi @chlee-tabin , the newest vignette should now be available via `vignette('celda-analysis')`. Let me know if you identify anything else odd about the vignette, and feel free to open issues for any other problems you may encounter!
