### ISSUE TITLE
Size of pbmc_data object

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#173]
It is too big as is. Let's cut it down to size and save it that way so the whole thing doesn't bog down the installation process. Need to set: 

pbmc_data <- pbmc_data[rowSums(pbmc_data>3) > 3,]

Also, need to convert to integer to save space

class(pbmc_data) = "integer"

**Comment by definitelysean** [comment]
Fixed by @ykoga07 in #174
