### ISSUE TITLE
sequencing heatmap

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#178]
fix breaks when "sequential" is chosen

**Comment by definitelysean** [comment]
@joshua-d-campbell Do you mind taking this one still? Or maybe @Irisapo can tackle it? Can you describe the problem a little more?

**Comment by joshua-d-campbell** [comment]
Simple fix. The "if" statement starting on 207:

if(is.null(breaks)){
  breaks <- seq(lbound.range, ubound.range, length.out = col.len)
}  

Needs to be moved outside of the scope of the previous if statement. So after the "}" on line 210.
