### ISSUE TITLE
no y (gene clustering) for simulated celda_CG data 

### ISSUE THREAD

**Issue by Irisapo** [compbiomed/celda#180]
There is no y (gene clustering labels) and no warning for simulated celda_CG data when using this line of code:
sim_CeldaCG <- simulateCells(model = "celda_CG", S=10, G=1000, K=5,L=5, seed=77)    
# length(sim_CeldaCG$y)==0

**Comment by definitelysean** [comment]
Hi Iris, I ran your example code but I didn't get the same error -- it seems like only under certain conditions, the Y is empty. I'll see if I can try to fix it.

**Comment by definitelysean** [comment]
Just an update: I ran simulateCells("celda_CG") 100 times and wasn't able to reproduce this.

**Comment by Irisapo** [comment]
@definitelysean  Yes, the problem solved when I update it with head on master
