### ISSUE TITLE
Refactor Vignette to use Pre-generated Data

### ISSUE THREAD

**Issue by definitelysean** [compbiomed/celda#184]
Currently the vignette takes a long time to build, I think due to actual `celda()` calls being run. We should pre-generate the results, load them in the background, and skip execution of those chunks in the vignette.

**Comment by definitelysean** [comment]
@ykoga07 Per Hadley's suggestion, you can pre-generate a celda_list object and put it in inst/extdata, and then load it in the vignette (rather than actually run celda) http://r-pkgs.had.co.nz/data.html

**Comment by ykoga07** [comment]
Pull request #202 fixes this issue.
