### ISSUE TITLE
count checksum

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#190]
1) The checksum is not being calculated and stored in the celda models. 
2) The checksum should be calculated after the counts matrix has been preprocessed (i.e. converted to integer)
3) Only a warning should be thrown if the checksum doesn't match, but an error should be thrown if different numbers of columns or rows are present

**Comment by definitelysean** [comment]
@joshua-d-campbell The counts are currently stored on the celda_list and not the models, so I can see why that wouldn't be useful.

Ideally I'd move the processCounts() code to the celda() wrapper function so we only have to calculate the checksum once, however that means that anytime someone calls e.g. celda_C() directly, the counts won't' be processed. 

I'll add a switch to the model functions that lets them know whether they need to process the counts ahead of time.
