### ISSUE TITLE
Include Cross-validation For Perplexity Evaluation

### ISSUE THREAD

**Issue by definitelysean** [compbiomed/celda#197]
In calculatePerplexity, implement a cross-validation strategy to compliment the existing resampling strategy (we're hoping they roughly correlate). 

Include a visualization of cross-validation based perplexity evaluation in a new function, calculatePerplexityWithCrossValidation() (or similar).

**Comment by joshua-d-campbell** [comment]
Don't need to implement it systematically yet. Please just try it out first and compare to subsampling scheme in two datasets.

**Comment by definitelysean** [comment]
I visualized a comparison of the cross-validation versus resampling for evaluating perplexity [here](https://www.dropbox.com/s/ohsaa9oo9hy3tgs/resampling_vs_xvalidation_perplexity.pdf?dl=0).

The code is available on branch x-validation.
