### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pwl** [compbiomed/celda#199]
Hi, I wanted to understand the model you're using but I cannot find any documentation on it.  I'm not a regular R user so maybe it's just me being unable to efficiently go browse the vignettes.  Is there a single place where I could read about the algorithm?  Or perhaps a paper that would explain how it works/performs?  Or maybe a tutorial with examples how to use it and how to interpret the results?

**Comment by definitelysean** [comment]
Hi @pwl , thanks for checking our package out. The celda model is not yet published, though our group is currently in progress on a manuscript that should be available in the coming months. Until that time, the model derivation will not be available; I'm sorry about any inconvenience this might cause you. The model is heavily informed by the [Latent Dirichlet Allocation](https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation) model, which may be useful for you to learn more about in the meantime if you're not already familiar with it.

If, however, you are just curious about how to run the package, there's a walkthrough of a typical celda analysis in the vignettes. You can either browse the HTML vignette in the codebase here on GitHub, or install the package via `devtools::install_github()` (see the README instructions). Once it's installed, you can call `browseVignettes('celda')` to see the walkthrough.
