### ISSUE TITLE
Consistent ordering of function in celda_*.R scripts

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#213]
Possible order:
1) Main
2) Gibbs sampling
3) Simulate
4) Factorize matrix
5) Others

**Comment by definitelysean** [comment]
Agreed @joshua-d-campbell. There's a couple other ordering things like this too that I'll open additional issues for, but I'll take care of this one now.

**Comment by definitelysean** [comment]
Full list I'm working off of as a template:

1. Model Function
2. Gibbs sampling code
3. Cell simulation code
4. Factorize matrix
5. clusterProbability
6. calculateLoglikFromVariables
7. logLik
8. calculatePerplexity
9. reorder
10. finalClusterAssignment
11. getK
12. getL
13. celdaHeatmap
