### ISSUE TITLE
redundant "sample.label" processing code

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#216]
Let's put that into a function rather than repeating it in each model.

 if(is.null(sample.label)) {
    s = rep(1, ncol(counts))
    sample.label = s
  } else if(is.factor(sample.label)) {
    s = as.integer(sample.label)
  } else {
    sample.label = as.factor(sample.label)
    s = as.integer(sample.label)
  }

**Comment by definitelysean** [comment]
Very DRY, will do.
