### ISSUE TITLE
celda wrapper sample.label validation

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#219]
user should be able to submit a sample label without having to convert it to a numeric vector first

**Comment by definitelysean** [comment]
@joshua-d-campbell Can you give me a code chunk that breaks re: the sample label type? Right now, the validation in the wrapper only asks that the object is either numeric, a character vector, or a factor; is there another acceptable type?

**Comment by joshua-d-campbell** [comment]
> rc = simulateCells("celda_CG")
> res <- celda(counts = rc$counts, model = "celda_CG", nchains = 1, K = rc$K, L = rc$L, rc$sample.label)
Error in validateArgs(counts, model, sample.label, nchains, cores, seed,  :
  Invalid sample.label; parameter should be a numeric vector

**Comment by definitelysean** [comment]
@joshua-d-campbell I see the offending check which I'll remove.

It's curious that this isn't causing the unit tests to fail though, since they do something similar. I'll dig in a little bit.
