### ISSUE TITLE
Benchmark speed of rowsums/colsums in Rfast

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#228]
Newest version has rowsum feature

https://cran.r-project.org/web/packages/Rfast/Rfast.pdf

**Comment by definitelysean** [comment]
@joshua-d-campbell I can do this, but one thing I'm realizing is Rfast doesn't provide an analogus function to base::rowsum(), which calculates column sums across rows of a matrix for a grouping variable. This is the function I recall SAIL as having indicated being slow.

I can re-implement this grouping functionality and call Rfast::colsums internally, however I'm wondering whether the additional overhead would negate any benefits of using Rfast. Let me know if I should do this.

Alternatively, I wonder if we can rewrite this calculation to calculate the aggregate metrics at the end. I'm sure part of the slowdown is not only calculating the rowsums, but reordering the matrices ( rowsum(..., reorder=TRUE) ) that's contributing to the slowdown.

**Comment by joshua-d-campbell** [comment]
This does not appear to be faster.
