### ISSUE TITLE
Remove celda() Wrapper

### ISSUE THREAD

**Issue by definitelysean** [compbiomed/celda#235]
The celda() wrapper was originally conceived as a uniform interface to the celda_C/G/CG models, and would have allowed for addition of further models. However, we've realized that this design choice is relatively confusing, complicates argument parsing, and obfuscates each models' specifics. 

We should move all argument validation and parallelization code to discrete functions callable from any celda_* model, and call this code from each of the models. We can leave the wrapper in-place to soften the transition for users who may infrequently use the package and aren't aware of this change, with a warning message that the convention has shifted.

**Comment by joshua-d-campbell** [comment]
Just some more thoughts on how we can refactor this:

1) Celda_C/G/CG should just allow for a single combination of K/L to be specified. Multiple chains and cores are allow, but the best model is automatically selected and returned (so the result is always a single model). If ncores = 1, a regular for loop should be called so the output can be printed and seen. Note an extra output statement should be displayed letting the user know what chain is being started (if nchain > 1). If ncores > 1, then the doParallel for loop can be called. 

2) The celda wrapper can be renamed to something like 'celdaGridSearch'. The default should be max.iter = 20 so it runs relatively quickly. This output can be directly fed into the calculatePerplexityWithResampling function. It should also call different for loops depending on whether ncores = 1 or > 1 (like in point 1).

**Comment by definitelysean** [comment]
Implemented by @joshua-d-campbell in #289
