### ISSUE TITLE
Counts to integer type

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#236]
The counts are not being set to 'integer' type properly for some reason. I know the 'processCounts' function is supposed to do this, but it is not being done for some reason. This should not be optional (i.e. this should not be a flag in the arguments). Rather it should be a check for integer class and if not, then rounded converted to integer.

Also, the output counts of the simulation functions are not automatically set to 'integer'

**Comment by definitelysean** [comment]
@joshua-d-campbell it looks like the type checking in processCounts() was happening incorrectly. That function checked whether `class(counts) == "integer"`, but that should always return "matrix"; `typeof()` is the function intended.

I removed this as an optional parameter from all of the model functions and wrapper, and modified processCounts() to cast the matrix to integer using `storage.mode()`
