### ISSUE TITLE
Consistent/updated terminology

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#240]
The word "states" has become a bit convoluted and can mean different things to different people. Thus we should update the cluster terminology. Something like "gene modules" and "cell populations".

**Comment by definitelysean** [comment]
@joshua-d-campbell I started a key terms reference on the [GitHub wiki here`.](https://github.com/compbiomed/celda/wiki/Model-Terminology), including these terms. We can use it as a canonical reference for how terms should be specified in future code contributions. Feel free to add any more terms that end up seeming inconsistent. One clarifying question I have in this vein is about the term "state probabilities" (e.g. in plot_dr.R); should this be translated to "cell population probability" and "gene module probability" where appropriate?

**Comment by definitelysean** [comment]
Fixed by @ykoga07 , @AndrewGr12 and me in #297 and #308
