### ISSUE TITLE
Adding sampling noise to perplexity

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#252]
Since we are doing resampling instead of cross validation in the perplexity calculation, we may want to better control the level of noise being added to each resampling. For each cell, instead of using the cell's multinomial distribution directly, we can sample that cell's probability with a Dirichlet distribution

prop[,i] = rdirichlet(1, counts[,i] + alpha)

We can try different values of alpha and see the effect on the perplexity calculations.

**Comment by definitelysean** [comment]
@joshua-d-campbell Here's the K/L perplexity plots for various alpha with the resampling noise approach you suggested.

[resampled_alpha_res_perplexity_plots.pdf](https://github.com/compbiomed/celda/files/2152086/resampled_alpha_res_perplexity_plots.pdf)

**Comment by joshua-d-campbell** [comment]
Let's not implement this for now as it doesn't seem to have an effect of change the means of K/L combinations but just increases the std. dev.
