### ISSUE TITLE
Reimplement matrixSums functions in Rcpp

### ISSUE THREAD

**Issue by definitelysean** [compbiomed/celda#258]

**Comment by definitelysean** [comment]
Just got a C-level memory leak error when running simulateCells.celda_CG() for the following parameters:

- model="celda_CG"
- K = 5
- alpha = 0.1
- beta = 0.1
- G = 1000
- S = 5
- gamma = 5
- C.Range = c(1000000, 1000001) 

I'm not sure if this will reproduce (these types of bugs can be finnicky), but reimplementing in C++ may help avoid memory allocation bugs

**Comment by joshua-d-campbell** [comment]
Was fixed by using logSumExp function in matrixStats package in commit 4f38f00502c2ac88e97815cdff3d183b5a42ec7e
