### ISSUE TITLE
"incorrect number of dimensions" error when L = 1

### ISSUE THREAD

**Issue by zhewa** [compbiomed/celda#262]
celda.CG function throws the error "incorrect number of dimensions" when the range of L includes 1. This error message shows up after all other chains finished running which results in waste of computing power and time. Should check if L includes 1 up front or suppress the error when L = 1.

celda.res <- celda(counts = mmafilter,
                   model = "celda_CG",
                   K = 3:8,
                   L = 1:10,
                   max.iter = 10,
                   cores = 14, nchains = 10,
                   verbose = TRUE)
 
Log message for Celda_chain-9_K-8_L-1_index-59_Seed-12353_log
... Starting celda_CG to cluster cells and genes.
 ... Completed iteration: 1 | logLik: -76067582.9703099
... Completed iteration: 2 | logLik: -76067582.9703099
 ... Completed iteration: 3 | logLik: -76067582.9703099
 ... Completed iteration: 4 | logLik: -76067582.9703099
 ... Completed iteration: 5 | logLik: -76067582.9703099
 ... Completed iteration: 6 | logLik: -76067582.9703099
 ... Completed iteration: 7 | logLik: -76067582.9703099
... Completed iteration: 8 | logLik: -76067582.9703099
 ... Completed iteration: 9 | logLik: -76067582.9703099
 ... Determining if any cell clusters should be split.
Error in { : task 1 failed - "incorrect number of dimensions"
Calls: celda -> %dopar% -> <Anonymous>
Execution halted

This error log shows up for all chains and K where L = 1.

**Comment by definitelysean** [comment]
@joshua-d-campbell what should the intended behavior be here? Should celda stop and say "I need L >= 2?"

**Comment by definitelysean** [comment]
Answer to above: "yes, it should be an error"
