### ISSUE TITLE
Warning message for K <= 1

### ISSUE THREAD

**Issue by ykoga07** [compbiomed/celda#273]
Whenever celda is run, even if K was not run at/less than 1., this message shows up:
Warning messages:
1: In if (is.numeric(K) & K <= 1) { :
  the condition has length > 1 and only the first element will be used

**Comment by definitelysean** [comment]
@ykoga07 can you give me a full stacktrace? Is this in the celda() wrapper function, or elsewhere in the code? This should be easy to fix when you find it; just rewrite the statement as `if(isTRUE(is.numeric(K) & K <= 1)) {`
