### ISSUE TITLE
Function Resolution Error in rowSumsByGroup

### ISSUE THREAD

**Issue by ykoga07** [compbiomed/celda#278]
Error message: "Error in .Call("_rowSumByGroup", x, group) : "_rowSumByGroup" not resolved from current namespace (celda)" when running functions that use rowSumByGroup; this occurs locally but does not occur when running on scc

**Comment by definitelysean** [comment]
@ykoga07 how were you installing celda? Fresh, or with devtools::install* ? You may need to delete all the .so, .o, and .dll files in your src/ directory before you install

**Comment by definitelysean** [comment]
@ykoga07 I tried fresh installs of the master branch on a Windows machine and SCC, and I can't reproduce this error. Can you please let me know if you can reproduce this issue after following the installation instructions I provided above?
