### ISSUE TITLE
Type error in rowSumByGroup

### ISSUE THREAD

**Issue by Traestaree** [compbiomed/celda#279]
Working with the Ischemic dataset, error in rowSumByGroups:  
input: factorized <- factorizeMatrix(counts = mat, celda.mod = model, type = "proportions")
Error in rowSumByGroup(counts, group = y, L = L) : 
  INTEGER() can only be applied to a 'integer', not a 'double'

mat is a numeric matrix of size 4814 1572. @definitelysean

**Comment by definitelysean** [comment]
@Traestaree I'm thinking the problem is that the `factorizeMatrix()` functions don't run the counts matrices through `processCounts()` to cast them to integer first. Can you please provide the following information:

- The `traceback(max=1)` output after encountering this error
- The `storage.mode(mat)` output identifying the underlying storage mode for that counts matrix
- The celda model you're using

**Comment by Traestaree** [comment]
traceback(max=1): 4: rowSumByGroup(counts, group = y, L = L)
3: cCG.decomposeCounts(counts, s, z, y, K, L)
2: factorizeMatrix.celda_CG(counts = mat, celda.mod = model, type = "proportions")
1: factorizeMatrix(counts = mat, celda.mod = model, type = "proportions")
storage.mode(mat):  "double"

**Comment by definitelysean** [comment]
@Traestaree I added some code to our development branch which I think should fix your issue. Could you try reinstalling celda from the devel branch (e.g. `devtools::install_github("compbiomed/celda@devel")`) and letting me know if you encounter the same issue?

**Comment by Traestaree** [comment]
Same issue, and same traceback message.

**Comment by definitelysean** [comment]
@Traestaree tried to message you on Slack; could you email me the path to the dataset you're having trouble processing?

**Comment by definitelysean** [comment]
Hi @Traestaree, I was able to get factorizeMatrix() fixed and working on your data. Please reinstall celda from either the master or devel branch, and try again. Feel free to reopen this issue if you somehow encounter the same issue.
