### ISSUE TITLE
Count matrix checking/processing

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#347]
1) Checking for all zero rows/columns was removed with last celdaGridSearch refactor, but should be added back in, maybe in processCounts. Error should be thrown so the user can decide how to handle
2) If a matrix of type 'numeric' is used as input, celda_C/G/CG fails at the end. Probably due to the order in which processCounts and compareCountMatrix is called in the beginning. Needs to be consistent so that the checksum is calculated on either the original matrix or processed matrix in all functions. processCounts probably needs to be added to the down-stream functions whenever compareCountMatrix is called.

**Comment by definitelysean** [comment]
Fixed in #353 
@joshua-d-campbell most changes were in split_clusters.R and initialize_clusters.R. Also see above each model function's definition, where I've placed a very thin wrapper.
