### ISSUE TITLE
Remove visualizeModelPerformance() and Related

### ISSUE THREAD

**Issue by definitelysean** [compbiomed/celda#65]
Continuing from #30 , refactor visualize_performance() so it has different implementations _by performance metric_.  There's lots of weird behavior in the function currently to dance around the different methods' means of working.

**Comment by definitelysean** [comment]
We've settled primarily on log likelihood and perplexity for our key metrics in choosing K/L combinations, so we should actually just remove the old convoluted code around visualizeModelPerformance() and the like.

**Comment by joshua-d-campbell** [comment]
Agreed
